import './globals.css';
import "@/styles/styles.scss";

import { Header } from '@/components/defaults';

export const metadata = {
  title: 'SoundTypeLab',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
