import './globals.css';
import "@/styles/styles.scss";
import "react-toastify/dist/ReactToastify.css";

import Provider from '@/components/defaults/Provider';
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: 'SoundTypeLab',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider >
          {children}
          <ToastContainer />
        </Provider>
      </body>
    </html>
  )
}
