import './globals.css';
import "@/styles/styles.scss";

import Provider from '@/components/defaults/Provider';

export const metadata = {
  title: 'SoundTypeLab',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider >
          {children}
        </Provider>
      </body>
    </html>
  )
}
